### PR TITLE
orientation not output

### PR DESCRIPTION
**Pull request by anli77**
I wrote output, committed, and noticed the error and did not push change to GitHub before last PR.

### CODE REVIEW

**Comment by AndyHazz** [comment]
Coincidentally I'm trying to set up MagicMirror OS for the first time right now, I've been running a manual install on buster/pi3b for many years. It seems screen rotation is more complex on bullseye than it was on buster!

I spotted these commits and have tried all options mentioned but have been unable to get the screen to rotate.

Right now I have what looks like the latest recommendation from this commit in my `/opt/mm/run/.env` file:

```
# Use following params to set orientation, scaling, port of the xserver,
# example for XRANDR_PARAMS="--output HDMI-1 --rotate left --scale 1.9"
XRANDR_PARAMS="--orientation left"
XRANDR_DELAY=10s
```

... this just gives me a blank screen. Increasing to 20s made no difference.

The earlier guide for `--output HDMI-1 --rotate left --scale 1.9` just did nothing. MM still displayed but wasn't rotated.

**Comment by khassel** [comment]
Can you provide output of
- `docker ps -a`
- `docker logs xserver`
- `docker logs mm`

**Comment by AndyHazz** [comment]
```
$ docker ps -a
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS                      PORTS     NAMES
6f83db5758cf   karsten13/magicmirror:latest   "/usr/bin/tini -- ./…"   40 seconds ago   Up 36 seconds                         mm
eb13ec345dbb   karsten13/magicmirror:latest   "/usr/bin/tini -- ./…"   40 seconds ago   Exited (0) 15 seconds ago             init
e81feef3919e   karsten13/xserver:latest       "/entrypoint.sh"         40 seconds ago   Up 39 seconds                         xserver
```

```
$ docker logs xserver

X.Org X Server 1.21.1.13
X Protocol Version 11, Revision 0
Current Operating System: Linux e81feef3919e 6.6.31+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64
Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_headphones=0 snd_bcm2835.enable_headphones=1 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_hdmi=0  vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=abc12d04-02 rootfstype=ext4 fsck.repair=yes rootwait cfg80211.ieee80211_regdom=GB
 
Current version of pixman: 0.43.2
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Fri Oct 11 21:59:32 2024
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
MESA-LOADER: failed to open vc4: Error loading shared library /usr/lib/xorg/modules/dri/vc4_dri.so: No such file or directory (search paths /usr/lib/xorg/modules/dri, suffix _dri)
MESA-LOADER: failed to open kms_swrast: Error loading shared library /usr/lib/xorg/modules/dri/kms_swrast_dri.so: No such file or directory (search paths /usr/lib/xorg/modules/dri, suffix _dri)
MESA-LOADER: failed to open swrast: Error loading shared library /usr/lib/xorg/modules/dri/swrast_dri.so: No such file or directory (search paths /usr/lib/xorg/modules/dri, suffix _dri)
couldn't get display device
```

```
$ docker logs mm
[entrypoint 23:04:24.010] [INFO]   copy default modules
[entrypoint 23:04:24.240] [INFO]   copy css files

> magicmirror@2.29.0 start
> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[2024-10-11 23:04:39.167] [LOG]   Starting MagicMirror: v2.29.0 
[2024-10-11 23:04:39.230] [LOG]   Loading config ... 
[2024-10-11 23:04:39.238] [LOG]   config template file not exists, no envsubst 
[2024-10-11 23:04:41.104] [INFO]  Checking config file /opt/magic_mirror/config/config.js ... 
[2024-10-11 23:04:41.264] [INFO]  Your configuration file doesn't contain syntax errors :) 
[2024-10-11 23:04:41.266] [INFO]  Checking modules structure configuration ... 
[2024-10-11 23:04:41.522] [INFO]  Your modules structure configuration doesn't contain errors :) 
[2024-10-11 23:04:41.531] [LOG]   Loading module helpers ... 
[2024-10-11 23:04:41.534] [LOG]   No helper found for module: alert. 
[2024-10-11 23:04:41.553] [LOG]   Initializing new module helper ... 
[2024-10-11 23:04:41.555] [LOG]   Module helper loaded: updatenotification 
[2024-10-11 23:04:41.557] [LOG]   No helper found for module: clock. 
[2024-10-11 23:04:42.030] [LOG]   Initializing new module helper ... 
[2024-10-11 23:04:42.032] [LOG]   Module helper loaded: calendar 
[2024-10-11 23:04:42.034] [LOG]   No helper found for module: compliments. 
[2024-10-11 23:04:42.035] [LOG]   No helper found for module: weather. 
[2024-10-11 23:04:42.349] [LOG]   Initializing new module helper ... 
[2024-10-11 23:04:42.350] [LOG]   Module helper loaded: newsfeed 
[2024-10-11 23:04:42.351] [LOG]   All module helpers loaded. 
[2024-10-11 23:04:42.370] [LOG]   Starting server on port 8080 ...  
[2024-10-11 23:04:45.742] [LOG]   Server started ... 
[2024-10-11 23:04:45.743] [LOG]   Connecting socket for: updatenotification 
[2024-10-11 23:04:45.745] [LOG]   Starting module helper: updatenotification 
[2024-10-11 23:04:45.747] [LOG]   Connecting socket for: calendar 
[2024-10-11 23:04:45.748] [LOG]   Starting node helper for: calendar 
[2024-10-11 23:04:45.750] [LOG]   Connecting socket for: newsfeed 
[2024-10-11 23:04:45.751] [LOG]   Starting node helper for: newsfeed 
[2024-10-11 23:04:45.753] [LOG]   Sockets connected & modules started ... 
[2024-10-11 23:04:46.367] [LOG]   Launching application. 
[2024-10-11 23:04:47.978] [INFO]  System information:
### SYSTEM:   manufacturer: ; model: Docker Container; virtual: false
### OS:       platform: linux; distro: Debian GNU/Linux; release: 12; arch: arm64; kernel: 6.6.31+rpt-rpi-v8
### VERSIONS: electron: 31.6.0; used node: 20.17.0; installed node: 22.9.0; npm: 10.8.3; pm2: 
### OTHER:    timeZone: Europe/London; ELECTRON_ENABLE_GPU: undefined 
[2024-10-11 23:04:53.110] [LOG]   Create new calendarfetcher for url: https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics - Interval: 604800000 
[2024-10-11 23:04:53.907] [LOG]   Create new newsfetcher for url: https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000 
[2024-10-11 23:04:53.923] [INFO]  updatenotification: Updater Class Loaded! 
[2024-10-11 23:04:53.925] [INFO]  updatenotification: Checking PM2 using... 
[2024-10-11 23:04:53.931] [INFO]  updatenotification: Running in docker container, not using PM2 ... 
[2024-10-11 23:04:53.933] [INFO]  Checking git for module: MagicMirror 
[2024-10-11 23:04:54.250] [INFO]  Calendar-Fetcher: Broadcasting 13 events from https://ics.calendarlabs.com/76/mm3137/US_Holidays.ics. 
[2024-10-11 23:04:55.731] [INFO]  Newsfeed-Fetcher: Broadcasting 24 items. 
```

**Comment by khassel** [comment]
This looks all o.k.

You could try to get the latest images and force a restart of the containers with

```bash
cd /opt/mm/run
docker compose pull
docker compose up -d --force-recreate
```

**Comment by AndyHazz** [comment]
That hasn't made any difference unfortunately

```
$ cd /opt/mm/run
docker compose pull
docker compose up -d --force-recreate
[+] Pulling 3/3
 ✔ magicmirror Skipped - Image is already being pulled by init                                                                                                                                0.0s 
 ✔ xserver Pulled                                                                                                                                                                             1.2s 
 ✔ init Pulled                                                                                                                                                                                1.2s 
[+] Running 3/3
 ✔ Container mm       Started                                                                                                                                                                18.7s 
 ✔ Container xserver  Started                                                                                                                                                                17.6s 
 ✔ Container init     Exited                                                                                                                                                                 17.7s 
```
Screen is still blank after mm starts ...

**Comment by anli77** [comment]
If you login to the xserver container and flip the screen to normal does MM render the data? (it will be upside down or whatever) 

If it does you are likely hitting the same issue I noted in https://github.com/guysoft/MagicMirrorOS/pull/69 My MM pulls a lot of calendar and API data and if something is slow it can end up in this issue, so I set my delay to 60s, by that time it has given up on the data fetch and rendered an error instead. 

Once MM has rendered completely once, the issue does not come back.

**Comment by khassel** [comment]
maybe the fix with the new env var is not pulled, so you can try

```bash
cd /opt/mm/run
git pull
docker compose up -d --force-recreate
```

If this does not work please provide output of `docker compose config`.

**Comment by AndyHazz** [comment]
Maybe a combination of things - I reflashed my SD card from scratch (it looked like there was a slightly newer img for download on gitlab) and noticed in the .env file there was a new default `XRANDR_DELAY="5s"` where before I'd had to enter that line myself, so @khassel you were probably right that I didn't have the latest fix with this env var.

It still didn't work at 10s or 20s but it did work at 60s so you were right about the extra delay needed there @anli77, at least - the screen is oriented correctly using `XRANDR_PARAMS="--orientation right"`, but it looks like something else needs to be done as the magicmirror output is still 1920x1080 aligned top left on what is now a 1080x1920 display, so only the left half of the magicmirror is on screen ...

**Comment by khassel** [comment]
You can try XRANDR_PARAMS="--output HDMI-1 --rotate left --scale 1.9" but this will only use the half of the screen.

Best solution I found so far is [using css for rotating mm](https://forum.magicmirror.builders/topic/9707/save-performance-when-rotating-screen-e-g-on-raspberry-pi?page=1), so remove the XRANDR_PARAMS in the `.env` file and add this to `/opt/mm/mounts/css/custom.css`:

```css
 body {
        margin: 0;
	position: absolute;
 	transform: rotate(90deg);
 	transform-origin: bottom left;
	width: 100vh;
	height: 100vw;
	object-fit: cover;
	top: -100vw;
        visibility: visible;
 }
```

go to `/opt/mm/run` and restart the containers with `docker compose up -d --force-recreate`

**Comment by AndyHazz** [comment]
ahh, yes that works - I wonder then if this is the method that should be in the rotation section of the readme? Unless your display is square, it seems the xrandr method won't really be suitable for anyone?

**Comment by khassel** [comment]
well, maybe this depends on pi version and monitor, I would be interested in the setup of @anli77 where xrandr seems to work (?)

**Comment by anli77** [comment]
PI 3b+ with 7" screen, https://thepihut.com/products/official-raspberry-pi-7-touchscreen-display, the reason it works for me is that I flip it 180 degrees, so the aspect ratio is the same, rotating the rendered output 90 degrees will create a new aspect ratio, I suspect it depends on the display driver in X if the AR is communicated correctly to apps, like the browser rendering MM output?

**Comment by khassel** [comment]
So we have 2 options for orientation
- `custom.css`: smart solution with no delay, may not working for all use cases (e.g. iframes may not in the right orientation)
- `xrandr` *and* `electronOptions` in `config.js`: you have to fiddle with the delay param and do the setup at 2 places

When using `xrandr` the screen is rotated but MagicMirror seems not know about this. So you have a rotated screen but using only half the space of the screen. The solution is to add

```js
  electronOptions: { fullscreen: false, width: 1080, height: 1920 },
```

to your `config.js` where you have to set the values for width and height. In above example my normal screen resolution is 1920x1080.

**Pull request merged**
