### PR TITLE
Fix timedate command in readme

### PR DESCRIPTION
**Pull request by nsauter**
This commit fixes the timedate command in README.rst. The working one is timedatectl.

### CODE REVIEW

**Comment by guysoft** [comment]
@khassel is this right? I don't have a running instance

**Comment by khassel** [comment]
thats correct:

```bash
pi@magicmirroros:~ $ timedate --help
-bash: timedate: command not found
pi@magicmirroros:~ $ timedatectl --help
timedatectl [OPTIONS...] COMMAND ...

Query or change system time and date settings.

  -h --help                Show this help message
     --version             Show package version
     --no-pager            Do not pipe output into a pager
     --no-ask-password     Do not prompt for password
  -H --host=[USER@]HOST    Operate on remote host
  -M --machine=CONTAINER   Operate on local container
     --adjust-system-clock Adjust system clock when changing local RTC mode
     --monitor             Monitor status of systemd-timesyncd
  -p --property=NAME       Show only properties by this name
  -a --all                 Show all properties, including empty ones
     --value               When showing properties, only print the value

Commands:
  status                   Show current time settings
  show                     Show properties of systemd-timedated
  set-time TIME            Set system time
  set-timezone ZONE        Set system time zone
  list-timezones           Show known time zones
  set-local-rtc BOOL       Control whether RTC is in local time
  set-ntp BOOL             Enable or disable network time synchronization

systemd-timesyncd Commands:
  timesync-status          Show status of systemd-timesyncd
  show-timesync            Show properties of systemd-timesyncd

See the timedatectl(1) man page for details.
```

But I have another question to the timezone section in the readme:

>        2. sudo ~/magicmirror/run/docker-compose.yml and add an entry under environment: for TZ: <your timezone>

The line contains a typo, should be `nano` instead of `sudo`.
This line sets the timezone in the container and is needed if this timezone differs from the timezone of the pi.

>        3. sudo timedatectl set-timezone <your timezone>

This line sets the timezone of the pi.

I think you don't need both lines, either you set the correct timezone of your pi (line 3., preferred solution) **or** the timezone of the container (line 2.).

**Comment by nsauter** [comment]
oh, totally missed the `sudo` thing. I'm wondering how that Readme Part found its way in with so many mistakes but my Change seemed Like a bigger deal tbh.

Anyway: Setting the timezone only on the Pi resulted in a time Offset of one hour for me. I Had to Set it in the docker too. But i dont know what Happens If its the other way around.

**Comment by khassel** [comment]
> oh, totally missed the sudo thing. I'm wondering how that Readme Part found its way in with so many mistakes but my Change  seemed Like a bigger deal tbh.

may you can correct the sudo thing in this PR?

> Anyway: Setting the timezone only on the Pi resulted in a time Offset of one hour for me. I Had to Set it in the docker too. But i dont know what Happens If its the other way around.

will check this part and we update this later if necessary ...

**Comment by nsauter** [comment]
Sure, i going to do that tomorrow.

**Pull request merged**
